---
- name: Adding jenkins public key
  copy:
    content: '{{ jenkins_public_key }}'
    dest: '/var/lib/jenkins/.ssh/authorized_keys'
    owner: '{{ jenkins_user_name }}'
    group: '{{ jenkins_group_name }}'
    mode: '0600'

