---
- include: docker.yml
- include: docker-compose.yml

- name: remove orphan containers
  shell: docker rm -f $(docker ps -a -q)
  ignore_errors: yes

- name: remove orphan volume
  shell: docker volume rm $(docker volume ls | tail -n +2 | awk '{print $2}') 
  ignore_errors: yes

- name: docker evacuate script (useful for maintenance)
  copy:
    src: "docker-evacuate"
    dest: "/usr/local/bin"
    mode: 0755
    
