---
- include: docker.yml
- include: docker-compose.yml

- name: remove orphan containers
  shell: docker rm -f $(docker ps -a -q)

- name: remove orphan volume
  shell: docker volume rm $(docker volume ls | tail -n +2 | awk '{print $2}') 
