---
- include: docker.yml
- include: docker-compose.yml

- name: remove orphan containers
  shell: docker rm -f $(docker ps -a -q)
  ignore_errors: yes

- name: remove orphan volume
  shell: docker volume rm $(docker volume ls | tail -n +2 | awk '{print $2}')
  ignore_errors: yes

- name: docker evacuate script (useful for maintenance)
  copy:
    src: "docker-evacuate"
    dest: "/usr/local/bin"
    mode: 0755

- name: check free space in workers
  copy:
    src: "check_workers_disk_space"
    dest: "/usr/local/bin"
    mode: 0755

- name: crontab task to check free disk space in workers
  cron:
    name: "crontab task to check free disk space in workers"
    minute: "*"
    hour: "6"
    day: "*"
    month: "*"
    job: "/usr/local/bin/check_workers_disk_space"

- name: ensure jenkins user is member of Docker group
  user:
    name: '{{ jenkins_user_name }}'
    groups: docker,sudo
    append: yes
