---
- name: Updating Package Cache
  apt: update_cache=yes cache_valid_time=3600
  tags: debian-packages

- name: Installing software
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - xmlstarlet
    - expect
    - wget
    - software-properties-common
    - unzip
    - zip
    - jq
    - bridge-utils
  tags: debian-packages


- name: Installing Ubuntu 16 Packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - realpath
      - python-software-properties
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
  tags: debian-packages

- name: Installing JDK
  apt: name=default-jdk state=present install_recommends=no
  tags: debian-packages

- name: Installing jshon
  apt: name=jshon state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  tags: debian-packages

